version: 2
jobs:
  build:
    working_directory: ~/hinclude
    environment:
      PORT: 8080
    docker:
      - image: circleci/node:latest-browsers-legacy
    steps:
      - checkout
      - run:
          name: test
          command: npm test
